# Generated by Django 5.1.7 on 2025-05-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyrankedplayer',
            name='avg',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fantasyrankedplayer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fantasyrankedplayer',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
