# Generated by Django 5.1.7 on 2025-05-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_fantasyrankedplayer_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyrankedplayer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fantasyrankedplayer',
            name='rank',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
