# Generated by Django 5.1.7 on 2025-05-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_fantasyrankedplayer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyrankedplayer',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
