# Generated by Django 5.1.7 on 2025-05-29 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_fantasyrankedplayer_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fantasyrankedplayer',
            name='removed',
        ),
        migrations.CreateModel(
            name='DisplayedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_rank', models.PositiveIntegerField(unique=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.fantasyrankedplayer')),
            ],
        ),
    ]
