# Generated by Django 5.1.7 on 2025-05-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_updatetimestamp_remove_fantasyrankedplayer_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyrankedplayer',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
