# Generated by Django 5.1.7 on 2025-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_fantasyrankedplayer_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyrankedplayer',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
