# Generated by Django 5.1.7 on 2025-06-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_fantasyrankedplayer_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyrankedplayer',
            name='injury_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
