# Generated by Django 5.1.7 on 2025-06-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_fantasyrankedplayer_injury_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyrankedplayer',
            name='injury_duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fantasyrankedplayer',
            name='injury_status',
            field=models.CharField(blank=True, default='Healthy', max_length=50),
        ),
    ]
