# Generated by Django 5.1.7 on 2025-06-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
    ]
